export const REQUEST_GET_PROJECTS = 'REQUEST_GET_PROJECTS'
export const RECEIVE_GET_PROJECTS = 'RECEIVE_GET_PROJECTS'
export const RECEIVE_POST_PROJECT = 'RECEIVE_POST_PROJECT'
export const RECEIVE_DELETE_PROJECT = 'RECEIVE_DELETE_PROJECT'
export const RECEIVE_MODIFY_PROJECT = 'RECEIVE_MODIFY_PROJECT'

export const DELETE_PROJECTS = 'DELETE_PROJECTS'