export const REQUEST_GET_TASKS = 'REQUEST_GET_TASKS'
export const RECEIVE_GET_TASKS = 'RECEIVE_GET_TASKS'
export const RECEIVE_DELETE_TASK = 'RECEIVE_DELETE_TASK'
export const RECEIVE_POST_TASK = 'RECEIVE_POST_TASK'
export const RECEIVE_MODIFY_TASK = 'RECEIVE_MODIFY_TASK'
export const RECEIVE_VISIBILITY_TASK = 'RECEIVE_VISIBILITY_TASK'

export const DELETE_TASKS = 'DELETE_TASKS'
export const VISIBILITY_TASKS = 'VISIBILITY_TASKS'