export const REQUEST_GET_WORKDAYS = 'REQUEST_GET_WORKDAYS'
export const RECEIVE_GET_WORKDAYS = 'RECEIVE_GET_WORKDAYS'
export const REQUEST_PUT_WORKDAYS = 'REQUEST_PUT_WORKDAYS'
export const RECEIVE_PUT_WORKDAYS = 'RECEIVE_PUT_WORKDAYS'